config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'pictures#index'
  resources :pictures
  get 'categories/:category_id', to: 'pictures#index', as: 'category'
  get 'tags/:tag_id', to: 'pictures#index', as: 'tag'
  get 'users/:slug', to: 'pictures#index', as: 'user'

  resources :favoris

  get '/upload', to: 'pictures#new', as: 'upload'
  #get '/users/:slug', to: 'users#show', as: 'users'
  #get '/users/', to: 'users#index', as: 'user'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :pictures
  validates_presence_of :name
end

app/models/favori.rb
class Favori < ApplicationRecord
  belongs_to :picture
  belongs_to :user
end

app/models/picture.rb
class Picture < ApplicationRecord
  mount_uploader :image, ImageUploader

  belongs_to :category
  belongs_to :user
  has_many :favoris
  has_many :tag_pictures
  has_many :tags, through: :tag_pictures

    validates_presence_of :image

  def self.search(args)
    if args[:keywords]
      if args[:keywords].first == '#'
        Picture.joins(:tags).where('tags.name LIKE :query', query: "%#{args[:keywords].gsub(/#/, '')}%")
      else
        Picture.joins(:user).where('users.first_name  LIKE :query', query: "%#{args[:keywords]}%")
      end
    elsif args[:category_id]
      Picture.where(['category_id = ?', args[:category_id]])
    elsif args[:tag_id]
      Picture.joins(:tag_pictures).where(['tag_pictures.tag_id = ?', args[:tag_id]])
    elsif args[:slug]
      Picture.where(['user_id = ?', args[:slug].to_i])
    else
      Picture.all
    end
  end


end

app/models/tag.rb
class Tag < ApplicationRecord
  validates_presence_of :name
  has_many :tag_pictures
  has_many :pictures, through: :tag_pictures
end

app/models/tag_picture.rb
class TagPicture < ApplicationRecord
  belongs_to :picture
  belongs_to :tag

  def self.findByPictures(args)
    TagPicture.where('picture_id LIKE :query', query: args)
  end

  def self.findByTags(args)
    TagPicture.where('tag_id LIKE :query', query: args)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # before_action :authenticate_user!
  has_many :pictures
  has_many :favoris
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  
  def configure_permitted_parameters
     devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :email, :password, :password_confirmation])
  end
end

app/controllers/favoris_controller.rb
class FavorisController < ApplicationController
  def index
  end

  def create
    @favori = Favori.create!(favoris_params)
  end

  def destroy
    @favori = Favori.delete(params[:id])
  end

  private
    def favoris_params
      params.permit(:picture_id).merge(user_id: current_user.id)
    end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

  def index
    @pictures = Picture.search(params)
  end

  def new
    @picture = Picture.new
  end

  def create
    @picture = Picture.new(picture_params)

    if @picture.save
      redirect_to '/'
    else
      redirect_to upload_path
    end
  end

private
  def picture_params
    params.required(:picture).permit(:category_id, :image, tag_ids: [] ).merge(user_id: current_user.id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Ynsta
    = csrf_meta_tags
    %link{href: "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css", rel: "stylesheet", integrity: "sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u", crossorigin: "anonymous"}
    %link{href: "https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/paper/bootstrap.min.css", rel: "stylesheet", integrity: "sha384-awusxf8AUojygHf2+joICySzB780jVvQaVCAt1clU3QsyAitLGul28Qxb2r1e5g+", crossorigin: "anonymous"}
    %link{href: "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css", rel: "stylesheet", integrity: "sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN", crossorigin: "anonymous"}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .header
      = render partial: '/shared/header'
    .container.content{style: 'margin-top: 100px'}
      = yield


%script{src: "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js", integrity: "sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa", crossorigin: "anonymous"}

app/views/pictures/index.html.haml
- if params[:category_id]
  - if @pictures.first != nil
    %h2.fa.fa-folder-open.category-title
      = @pictures.first.category.name
    .tag-header
- elsif params[:tag_id]
  - Tag.all.each do |tag|
    - if params[:tag_id].to_i == tag.id
      %h2
        = "#" + tag.name.downcase
      .tag-header
- elsif params[:slug]
  .user-header
    %div.fa.fa-user-circle-o
    %h2.user-title
      = @pictures.first.user.first_name + " " + @pictures.first.user.last_name



= render partial: '/shared/show-pictures', locals: {pictures: @pictures}

app/views/pictures/new.html.haml
.row
  .col-xs-8.col-xs-offset-2
    %h3= 'Uploder une image'
-# - if @listing.errors.any?
-#   .row
-#     .col-xs-8.col-xs-offset-2.errors
-#       %h2
-#         = pluralize(@listing.errors.count, "error")
-#         = t('errors', count: @listing.errors.count)
-#       %ul
-#         - @listing.errors.full_messages.each do |msg|
-#           %li= msg
.row
  .col-xs-8.col-xs-offset-2
    = form_for @picture, class: 'form', html: {multipart: true} do |f|
      .form-group
        = f.label :category_id, class: 'form-label required'
        = f.collection_select :category_id, Category.all, :id, :name, {}, {class: 'form-control'}
      .form-group
        %ul.list-unstyled
          - Tag.all.each do |tag|
            %li
              = check_box_tag "picture[tag_ids][]", tag.id, f.object.tags.include?(tag)
              = tag.name

      .form-group
        = f.label :image, class: 'form-label required'
        = f.file_field :image, class: 'form-control'

      .form-group
        -# %span= t('required_field')
        = f.submit "Publier la photo", class: 'btn btn-primary pull-right'

app/views/shared/_header.html.haml
%nav.navbar.navbar-default.navbar-fixed-top
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => root_path}
        %i.fa.fa-instagram
        = 'Ynsta'
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
        - if Category.all != nil
          - Category.all.each do |category|
            - if params[:category_id] == category.id
              %li.active
                %a{:href => category_path(category.id)}
                  = category.name
            - else
              %li
                %a{:href => category_path(category.id)}
                  = category.name

        -# - if params[:category_id] == '1'
        -#   %li.active
        -#     %a{:href => category_path(1)} People
        -# - else
        -#   %li
        -#     %a{:href => category_path(1)} People
        -# - if params[:category_id] == '2'
        -#   %li.active
        -#     %a{:href => category_path(2)} Travel
        -# - else
        -#   %li
        -#     %a{:href => category_path(2)} Travel
        -# - if params[:category_id] == '3'
        -#   %li.active
        -#     %a{:href => category_path(3)} Food
        -# - else
        -#   %li
        -#     %a{:href => category_path(3)} Food


      %form.navbar-form.navbar-left{:role => "search"}
        = form_tag pictures_path, method: :get, class:'form form-hroizontal'  do
          .form-group
            .col-xs-10
              = text_field_tag 'keywords', nil, class: 'form-control', placeholder: "search"

      - if current_user
        %ul.nav.navbar-nav.navbar-right
          - if current_user.id == 1
            %li
              %a{href: '/admin'}
                %i.fa.fa-lock
                  = 'Admin'
          %li
            %a{href: upload_path} Uploader une image
          %li
            %a{href: user_path(current_user.id), style: 'font-weight: bold'}
              %i.fa.fa-user
              = current_user.first_name + " " + current_user.last_name
          %li
            %a.fa.fa-sign-out{href: destroy_user_session_path}

      - else
        %ul.nav.navbar-nav.navbar-right
          %li
            %a{href: new_user_registration_path} Inscription
          %li
            %a{href: new_user_session_path} Connexion

app/views/shared/_show-pictures.html.haml
.row
  - pictures.each do |picture|
    .col-xs-12.col-md-4
      .picture-container
        .picture
          = image_tag picture.image, class: 'img-responsive'
        .picture-footer
          .picture-like
            - if current_user
              - if ![Favori.find_by_picture_id(picture.id)].empty?
                - if Favori.where(:picture_id=>picture.id).pluck(:user_id).include?(current_user.id)
                  %a.fa.fa-heart.heart.full-heart{data: {do: 'unlike', id: Favori.where(:picture_id=>picture.id, :user_id=>current_user.id).pluck(:id).first}}
                - else
                  %a.fa.fa-heart-o.heart.empty-heart{data: {do: 'like', picture: picture.id}}
            - else
              %i.fa.fa-heart-o.heart.empty-heart
            %h3
              = Favori.where(:picture_id=>picture.id).count
          .picture-description
            %h3
              %a{href: user_path("#{picture.user.id}-#{picture.user.first_name.parameterize}")}
                = "By " + picture.user.first_name + " " + picture.user.last_name
            %p
              - Tag.all.each do |tag|
                - if picture.tags.pluck(:id).include?(tag.id)
                  %a.tag-name{href: tag_path(tag.id)}
                    = tag.name

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>